--stworzenie tabel 
CREATE TABLE IF NOT EXISTS buildings (
id SERIAL PRIMARY KEY,
geometry GEOMETRY(POLYGON),
name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS roads (
id SERIAL PRIMARY KEY,
geometry GEOMETRY(LINESTRING),
name VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS poi (
id SERIAL PRIMARY KEY,
geometry GEOMETRY(POINT),
name VARCHAR(20)
);
